# Importing Libraries

In [88]:
import pandas as pd
import numpy as np

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

# Loading the Dataset

In [89]:
df = pd.read_csv('accepted_2007_to_2018Q4_100k.csv')
df.head()

C:\Users\kushd\AppData\Local\Temp\ipykernel_10072\963731857.py:1: DtypeWarning: Columns (0: id) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('accepted_2007_to_2018Q4_100k.csv')

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_fico_range_low,sec_app_fico_range_high,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,92321477,NaN,16800.0,16800.0,16800.0,36 months,11.49,553.92,B,B5,DIRECTOR,9 years,RENT,112000.0,Verified,Nov-2016,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,debt_consolidation,Debt consolidation,432xx,NY,28.32,0.0,Apr-1994,675.0,679.0,3.0,41.0,NaN,14.0,0.0,10209.0,55.0,34.0,w,0.00,0.00,19120.303778,19120.30,16800.00,2320.30,0.0,0.0,0.0,Aug-2018,6295.17,NaN,Mar-2019,659.0,655.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,142814.0,2.0,5.0,3.0,4.0,3.0,132605.0,98.0,1.0,5.0,4979.0,55.0,18450.0,7.0,3.0,5.0,9.0,10985.0,2242.0,71.0,0.0,0.0,193.0,270.0,9.0,3.0,0.0,9.0,41.0,3.0,41.0,0.0,6.0,8.0,10.0,12.0,18.0,8.0,16.0,5.0,13.0,NaN,0.0,0.0,4.0,94.0,33.3,0.0,0.0,153821.0,142814.0,13450.0,135371.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,92235344,NaN,15000.0,15000.0,15000.0,60 months,15.99,364.70,C,C5,Environmental Health Manager,10+ years,MORTGAGE,48000.0,Source Verified,Oct-2016,Late (31-120 days),n,https://lendingclub.com/browse/loanDetail.acti...,NaN,debt_consolidation,Debt consolidation,807xx,CO,3.70,0.0,Feb-2000,715.0,719.0,0.0,NaN,NaN,3.0,0.0,3302.0,94.3,15.0,w,9687.98,9687.98,9833.580000,9833.58,5312.02,4521.56,0.0,0.0,0.0,Feb-2019,364.70,Apr-2019,Mar-2019,679.0,675.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,119299.0,0.0,0.0,0.0,0.0,27.0,0.0,NaN,0.0,0.0,2342.0,94.0,3500.0,0.0,7.0,0.0,0.0,39766.0,158.0,93.7,0.0,0.0,116.0,200.0,39.0,27.0,4.0,64.0,NaN,NaN,NaN,0.0,1.0,2.0,1.0,1.0,7.0,2.0,4.0,2.0,3.0,0.0,0.0,0.0,0.0,100.0,100.0,0.0,0.0,126500.0,3302.0,2500.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,99787125,NaN,24000.0,24000.0,24000.0,60 months,11.49,527.71,B,B5,Police Officer,10+ years,RENT,90000.0,Not Verified,Feb-2017,Current,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,debt_consolidation,Debt consolidation,913xx,CA,22.72,0.0,Oct-1998,730.0,734.0,0.0,NaN,NaN,7.0,0.0,25479.0,71.0,18.0,w,16004.70,16004.70,12744.980000,12744.98,7995.30,4749.68,0.0,0.0,0.0,Mar-2019,527.71,Apr-2019,Mar-2019,554.0,550.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,50053.0,0.0,3.0,0.0,1.0,21.0,24574.0,53.0,0.0,0.0,12280.0,61.0,35900.0,0.0,2.0,0.0,1.0,7150.0,10421.0,71.0,0.0,0.0,122.0,219.0,27.0,21.0,3.0,27.0,NaN,NaN,NaN,0.0,4.0,4.0,4.0,7.0,7.0,4.0,7.0,4.0,7.0,0.0,0.0,0.0,0.0,100.0,75.0,0.0,0.0,82451.0,50053.0,35900.0,46551.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,61534011,NaN,35000.0,35000.0,35000.0,36 months,7.89,1095.00,A,A5,"Director, Enterprise Operations",1 year,RENT,150000.0,Source Verified,Oct-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,credit_card,Credit card refinancing,068xx,CT,13.08,0.0,Aug-1988,720.0,724.0,0.0,NaN,NaN,7.0,0.0,37665.0,60.5,26.0,w,0.00,0.00,39381.551994,39381.55,35000.00,4381.55,0.0,0.0,0.0,Oct-2018,1094.90,NaN,Mar-2019,784.0,780.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,49787.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62300.0,NaN,NaN,NaN,2.0,7112.0,17410.0,67.0,0.0,0.0,153.0,326.0,5.0,5.0,2.0,37.0,NaN,12.0,NaN,0.0,3.0,4.0,4.0,12.0,5.0,6.0,19.0,4.0,7.0,0.0,0.0,0.0,1.0,100.0,75.0,0.0,0.0,82136.0,49787.0,52700.0,19836.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,76568593,NaN,25000.0,25000.0,25000.0,60 months,12.99,568.70,C,C2,bus driver,10+ years,RENT,67000.0,Not Verified,Apr-2016,Current,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,credit_card,Credit card refinancing,945xx,CA,15.46,3.0,Dec-1999,675.0,679.0,0.0,13.0,NaN,8.0,0.0,16557.0,49.4,15.0,w,12397.70,12397.70,19886.460000,19886.46,12602.30,7284.16,0.0,0.0,0.0,Mar-2019,568.70,Apr-2019,Mar-2019,744.0,740.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,23107.0,0.0,1.0,0.0,0.0,38.0,6550.0,56.0,0.0,0.0,5300.0,51.0,33500.0,0.0,0.0,0.0,0.0,2888.0,14476.0,50.1,0.0,0.0,120.0,196.0,51.0,38.0,0.0,51.0,13.0,NaN,13.0,0.0,4.0,6.0,5.0,9.0,4.0,7.0,11.0,6.0,8.0,0.0,0.0,0.0,0.0,73.3,20.0,0.0,0.0,45228.0,23107.0,29000.0,11728.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

# Exploratory Data Analysis

In [90]:
df.shape

(100000, 151)

In [91]:
df.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_fico_range_low,sec_app_fico_range_high,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,92321477,NaN,16800.0,16800.0,16800.0,36 months,11.49,553.92,B,B5,DIRECTOR,9 years,RENT,112000.0,Verified,Nov-2016,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,debt_consolidation,Debt consolidation,432xx,NY,28.32,0.0,Apr-1994,675.0,679.0,3.0,41.0,NaN,14.0,0.0,10209.0,55.0,34.0,w,0.00,0.00,19120.303778,19120.30,16800.00,2320.30,0.0,0.0,0.0,Aug-2018,6295.17,NaN,Mar-2019,659.0,655.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,142814.0,2.0,5.0,3.0,4.0,3.0,132605.0,98.0,1.0,5.0,4979.0,55.0,18450.0,7.0,3.0,5.0,9.0,10985.0,2242.0,71.0,0.0,0.0,193.0,270.0,9.0,3.0,0.0,9.0,41.0,3.0,41.0,0.0,6.0,8.0,10.0,12.0,18.0,8.0,16.0,5.0,13.0,NaN,0.0,0.0,4.0,94.0,33.3,0.0,0.0,153821.0,142814.0,13450.0,135371.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,92235344,NaN,15000.0,15000.0,15000.0,60 months,15.99,364.70,C,C5,Environmental Health Manager,10+ years,MORTGAGE,48000.0,Source Verified,Oct-2016,Late (31-120 days),n,https://lendingclub.com/browse/loanDetail.acti...,NaN,debt_consolidation,Debt consolidation,807xx,CO,3.70,0.0,Feb-2000,715.0,719.0,0.0,NaN,NaN,3.0,0.0,3302.0,94.3,15.0,w,9687.98,9687.98,9833.580000,9833.58,5312.02,4521.56,0.0,0.0,0.0,Feb-2019,364.70,Apr-2019,Mar-2019,679.0,675.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,119299.0,0.0,0.0,0.0,0.0,27.0,0.0,NaN,0.0,0.0,2342.0,94.0,3500.0,0.0,7.0,0.0,0.0,39766.0,158.0,93.7,0.0,0.0,116.0,200.0,39.0,27.0,4.0,64.0,NaN,NaN,NaN,0.0,1.0,2.0,1.0,1.0,7.0,2.0,4.0,2.0,3.0,0.0,0.0,0.0,0.0,100.0,100.0,0.0,0.0,126500.0,3302.0,2500.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,99787125,NaN,24000.0,24000.0,24000.0,60 months,11.49,527.71,B,B5,Police Officer,10+ years,RENT,90000.0,Not Verified,Feb-2017,Current,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,debt_consolidation,Debt consolidation,913xx,CA,22.72,0.0,Oct-1998,730.0,734.0,0.0,NaN,NaN,7.0,0.0,25479.0,71.0,18.0,w,16004.70,16004.70,12744.980000,12744.98,7995.30,4749.68,0.0,0.0,0.0,Mar-2019,527.71,Apr-2019,Mar-2019,554.0,550.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,50053.0,0.0,3.0,0.0,1.0,21.0,24574.0,53.0,0.0,0.0,12280.0,61.0,35900.0,0.0,2.0,0.0,1.0,7150.0,10421.0,71.0,0.0,0.0,122.0,219.0,27.0,21.0,3.0,27.0,NaN,NaN,NaN,0.0,4.0,4.0,4.0,7.0,7.0,4.0,7.0,4.0,7.0,0.0,0.0,0.0,0.0,100.0,75.0,0.0,0.0,82451.0,50053.0,35900.0,46551.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,61534011,NaN,35000.0,35000.0,35000.0,36 months,7.89,1095.00,A,A5,"Director, Enterprise Operations",1 year,RENT,150000.0,Source Verified,Oct-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,credit_card,Credit card refinancing,068xx,CT,13.08,0.0,Aug-1988,720.0,724.0,0.0,NaN,NaN,7.0,0.0,37665.0,60.5,26.0,w,0.00,0.00,39381.551994,39381.55,35000.00,4381.55,0.0,0.0,0.0,Oct-2018,1094.90,NaN,Mar-2019,784.0,780.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,49787.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62300.0,NaN,NaN,NaN,2.0,7112.0,17410.0,67.0,0.0,0.0,153.0,326.0,5.0,5.0,2.0,37.0,NaN,12.0,NaN,0.0,3.0,4.0,4.0,12.0,5.0,6.0,19.0,4.0,7.0,0.0,0.0,0.0,1.0,100.0,75.0,0.0,0.0,82136.0,49787.0,52700.0,19836.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,76568593,NaN,25000.0,25000.0,25000.0,60 months,12.99,568.70,C,C2,bus driver,10+ years,RENT,67000.0,Not Verified,Apr-2016,Current,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,credit_card,Credit card refinancing,945xx,CA,15.46,3.0,Dec-1999,675.0,679.0,0.0,13.0,NaN,8.0,0.0,16557.0,49.4,15.0,w,12397.70,12397.70,19886.460000,19886.46,12602.30,7284.16,0.0,0.0,0.0,Mar-2019,568.70,Apr-2019,Mar-2019,744.0,740.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,23107.0,0.0,1.0,0.0,0.0,38.0,6550.0,56.0,0.0,0.0,5300.0,51.0,33500.0,0.0,0.0,0.0,0.0,2888.0,14476.0,50.1,0.0,0.0,120.0,196.0,51.0,38.0,0.0,51.0,13.0,NaN,13.0,0.0,4.0,6.0,5.0,9.0,4.0,7.0,11.0,6.0,8.0,0.0,0.0,0.0,0.0,73.3,20.0,0.0,0.0,45228.0,23107.0,29000.0,11728.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [92]:
df['loan_status'].value_counts()

loan_status
Fully Paid                                             47647
Current                                                38783
Charged Off                                            11937
Late (31-120 days)                                       938
In Grace Period                                          381
Late (16-30 days)                                        187
Does not meet the credit policy. Status:Fully Paid        88
Does not meet the credit policy. Status:Charged Off       35
Default                                                    3
Name: count, dtype: int64

# Creating Target Variable

In [93]:
good_loan = ['Fully Paid', 'Current']

df['target'] = df['loan_status'].apply(lambda x: 1 if x in good_loan else 0)

df['target'].value_counts()

C:\Users\kushd\AppData\Local\Temp\ipykernel_10072\3185295872.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['target'] = df['loan_status'].apply(lambda x: 1 if x in good_loan else 0)

target
1    86430
0    13570
Name: count, dtype: int64

In [94]:
cols_to_drop = ['id', 'member_id', 'url', 'desc', 'title', 
                'zip_code', 'emp_title', 'loan_status']

df = df.drop(columns=cols_to_drop)

print(df.shape)

(100000, 144)

# Checking the Missing Values

In [95]:
missing = df.isnull().sum()
missing_percent = (df.isnull().sum() / len(df)) * 100

missing_df = pd.DataFrame({'missing_count': missing, 'missing_percent': missing_percent})
missing_df = missing_df[missing_df['missing_count'] > 0].sort_values('missing_percent', ascending=False)

print(missing_df)

                                            missing_count  missing_percent
orig_projected_additional_accrued_interest          99608           99.608
payment_plan_start_date                             99501           99.501
hardship_end_date                                   99501           99.501
hardship_type                                       99501           99.501
hardship_reason                                     99501           99.501
...                                                   ...              ...
out_prncp_inv                                           1            0.001
out_prncp                                               1            0.001
initial_list_status                                     1            0.001
revol_bal                                               1            0.001
loan_amnt                                               1            0.001

[143 rows x 2 columns]

In [96]:
threshold = 80

cols_to_drop_missing = missing_df[missing_df['missing_percent'] > threshold].index.tolist()

df = df.drop(columns=cols_to_drop_missing)

print(df.shape)
print(df.isnull().sum().sum())

(100000, 107)
1000851

# Filling Missing Values

In [97]:
# fill numerical columns with median
num_cols = df.select_dtypes(include=['float64', 'int64']).columns
df[num_cols] = df[num_cols].fillna(df[num_cols].median())

# fill categorical columns with mode
cat_cols = df.select_dtypes(include=['object']).columns
df[cat_cols] = df[cat_cols].fillna(df[cat_cols].mode().iloc[0])

print(df.isnull().sum().sum())  # should be 0
print(df.shape)

C:\Users\kushd\AppData\Local\Temp\ipykernel_10072\4192918696.py:6: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = df.select_dtypes(include=['object']).columns

0
(100000, 107)

# Checking Categorical Columns

In [98]:
cat_cols = df.select_dtypes(include=['object']).columns
print(f"Total categorical columns: {len(cat_cols)}")
print(cat_cols)

Total categorical columns: 19
Index(['term', 'grade', 'sub_grade', 'emp_length', 'home_ownership',
       'verification_status', 'issue_d', 'pymnt_plan', 'purpose', 'addr_state',
       'earliest_cr_line', 'initial_list_status', 'last_pymnt_d',
       'next_pymnt_d', 'last_credit_pull_d', 'application_type',
       'hardship_flag', 'disbursement_method', 'debt_settlement_flag'],
      dtype='str')

C:\Users\kushd\AppData\Local\Temp\ipykernel_10072\1966658214.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = df.select_dtypes(include=['object']).columns

# Checking unique values in categorical columns

In [99]:
for col in cat_cols:
    print(f"{col} : {df[col].nunique()} unique values")
    print(df[col].unique())
    print()

term : 2 unique values
<ArrowStringArray>
[' 36 months', ' 60 months']
Length: 2, dtype: str

grade : 7 unique values
<ArrowStringArray>
['B', 'C', 'A', 'E', 'D', 'G', 'F']
Length: 7, dtype: str

sub_grade : 35 unique values
<ArrowStringArray>
['B5', 'C5', 'A5', 'C2', 'E4', 'A2', 'B4', 'B2', 'A3', 'A1', 'D1', 'B1', 'C1',
 'D2', 'E3', 'C4', 'B3', 'C3', 'E2', 'D3', 'A4', 'D4', 'E1', 'D5', 'G5', 'E5',
 'F1', 'G1', 'F4', 'F3', 'G4', 'F5', 'F2', 'G2', 'G3']
Length: 35, dtype: str

emp_length : 11 unique values
<ArrowStringArray>
[  '9 years', '10+ years',    '1 year',  '< 1 year',   '3 years',   '2 years',
   '4 years',   '8 years',   '5 years',   '7 years',   '6 years']
Length: 11, dtype: str

home_ownership : 6 unique values
<ArrowStringArray>
['RENT', 'MORTGAGE', 'OWN', 'ANY', 'OTHER', 'NONE']
Length: 6, dtype: str

verification_status : 3 unique values
<ArrowStringArray>
['Verified', 'Source Verified', 'Not Verified']
Length: 3, dtype: str

issue_d : 138 unique values
<ArrowStringArray>
['Nov-2016', 'Oct-2016', 'Feb-2017', 'Oct-2015', 'Apr-2016', 'Apr-2018',
 'Jul-2016', 'Nov-2014', 'Jul-2014', 'May-2015',
 ...
 'Apr-2009', 'Sep-2007', 'Oct-2007', 'Oct-2008', 'May-2008', 'Jul-2007',
 'Aug-2007', 'Aug-2008', 'Nov-2007', 'Jun-2007']
Length: 138, dtype: str

pymnt_plan : 2 unique values
<ArrowStringArray>
['n', 'y']
Length: 2, dtype: str

purpose : 14 unique values
<ArrowStringArray>
['debt_consolidation',        'credit_card',   'home_improvement',
              'other',            'medical',     'major_purchase',
     'small_business',            'wedding',             'moving',
           'vacation',                'car',              'house',
   'renewable_energy',        'educational']
Length: 14, dtype: str

addr_state : 50 unique values
<ArrowStringArray>
['NY', 'CO', 'CA', 'CT', 'TX', 'WA', 'GA', 'MD', 'IL', 'NJ', 'MN', 'NC', 'KS',
 'OH', 'PA', 'KY', 'VA', 'MI', 'MO', 'OR', 'SC', 'AZ', 'MS', 'LA', 'FL', 'MA',
 'NV', 'AL', 'NM', 'WV', 'UT', 'ME', 'WI', 'IN', 'TN', 'NH', 'NE', 'OK', 'MT',
 'AR', 'VT', 'RI', 'ID', 'DE', 'WY', 'HI', 'DC', 'SD', 'AK', 'ND']
Length: 50, dtype: str

earliest_cr_line : 648 unique values
<ArrowStringArray>
['Apr-1994', 'Feb-2000', 'Oct-1998', 'Aug-1988', 'Dec-1999', 'Jan-1977',
 'Feb-2008', 'Mar-1990', 'Feb-1998', 'Nov-2002',
 ...
 'Aug-1962', 'Apr-1960', 'Sep-1963', 'Mar-1962', 'Oct-1960', 'Nov-1964',
 'May-1971', 'Feb-1968', 'May-1965', 'Feb-1945']
Length: 648, dtype: str

initial_list_status : 2 unique values
<ArrowStringArray>
['w', 'f']
Length: 2, dtype: str

last_pymnt_d : 133 unique values
<ArrowStringArray>
['Aug-2018', 'Feb-2019', 'Mar-2019', 'Oct-2018', 'Nov-2017', 'Aug-2017',
 'Aug-2015', 'Jul-2016', 'Jul-2014', 'Dec-2018',
 ...
 'Sep-2009', 'Mar-2009', 'Jul-2009', 'Apr-2008', 'May-2008', 'Apr-2009',
 'Dec-2008', 'Jan-2008', 'Mar-2008', 'Jul-2008']
Length: 133, dtype: str

next_pymnt_d : 59 unique values
<ArrowStringArray>
['Apr-2019', 'Mar-2019', 'May-2012', 'Jan-2012', 'Jul-2012', 'May-2013',
 'Feb-2013', 'Mar-2013', 'May-2011', 'Jun-2012', 'Aug-2012', 'Jun-2013',
 'Jan-2011', 'Jul-2011', 'Dec-2010', 'Feb-2012', 'Aug-2011', 'Jun-2011',
 'Sep-2012', 'Sep-2011', 'Oct-2009', 'Mar-2011', 'Dec-2012', 'May-2019',
 'Aug-2010', 'Nov-2010', 'Mar-2010', 'Sep-2018', 'May-2015', 'Nov-2011',
 'Nov-2015', 'Jan-2010', 'Sep-2010', 'Apr-2011', 'Nov-2013', 'Mar-2009',
 'Oct-2013', 'Dec-2008', 'Dec-2009', 'Mar-2014', 'Dec-2011', 'Feb-2011',
 'Mar-2012', 'Apr-2013', 'Aug-2009', 'Apr-2015', 'Jan-2013', 'Oct-2011',
 'Sep-2013', 'Jul-2009', 'Apr-2012', 'Jul-2010', 'May-2009', 'Jan-2009',
 'Oct-2008', 'Jan-2008', 'Nov-2014', 'Mar-2008', 'Nov-2009']
Length: 59, dtype: str

last_credit_pull_d : 122 unique values
<ArrowStringArray>
['Mar-2019', 'Aug-2015', 'Jan-2019', 'Oct-2016', 'Jun-2017', 'Sep-2018',
 'Feb-2016', 'Dec-2018', 'Jul-2018', 'Nov-2018',
 ...
 'Mar-2009', 'Jun-2009', 'Dec-2011', 'Aug-2009', 'Jun-2007', 'Apr-2011',
 'Aug-2007', 'Sep-2011', 'Apr-2009', 'May-2009']
Length: 122, dtype: str

application_type : 2 unique values
<ArrowStringArray>
['Individual', 'Joint App']
Length: 2, dtype: str

hardship_flag : 2 unique values
<ArrowStringArray>
['N', 'Y']
Length: 2, dtype: str

disbursement_method : 2 unique values
<ArrowStringArray>
['Cash', 'DirectPay']
Length: 2, dtype: str

debt_settlement_flag : 2 unique values
<ArrowStringArray>
['N', 'Y']
Length: 2, dtype: str

# Drop Date & High Cardinality Columns

In [100]:
cols_to_drop_now = ['addr_state', 'issue_d', 'earliest_cr_line', 
                    'last_pymnt_d', 'next_pymnt_d', 'last_credit_pull_d']

df = df.drop(columns=cols_to_drop_now)

print(df.shape)

(100000, 101)

# Label Encoding Categorical Columns

In [101]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

cat_cols = df.select_dtypes(include=['object']).columns

for col in cat_cols:
    df[col] = le.fit_transform(df[col])

print(df.select_dtypes(include=['object']).columns.tolist())  # should be empty
print(df.shape)

C:\Users\kushd\AppData\Local\Temp\ipykernel_10072\4132554851.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = df.select_dtypes(include=['object']).columns

[]
(100000, 101)

# Separating Features and Target

In [102]:
X = df.drop(columns=['target'])
y = df['target']

print(X.shape)
print(y.shape)
print(y.value_counts())

(100000, 100)
(100000,)
target
1    86430
0    13570
Name: count, dtype: int64

# Train and Test Split

In [103]:
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                     test_size=0.2, 
                                                     random_state=42)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(80000, 100)
(20000, 100)
(80000,)
(20000,)

# Feature Scaling

In [104]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print(X_train.mean().round(2))
print(X_train.std().round(2))

0.0
0.99

# Converting to Pytorch tensors

In [105]:
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train.values, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test.values, dtype=torch.float32)

print(X_train_tensor.shape)
print(X_test_tensor.shape)
print(y_train_tensor.shape)
print(y_test_tensor.shape)

torch.Size([80000, 100])
torch.Size([20000, 100])
torch.Size([80000])
torch.Size([20000])

# Creating DataLoader

In [106]:
from torch.utils.data import TensorDataset

train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
test_dataset = TensorDataset(X_test_tensor, y_test_tensor)

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

print(f"Total training batches: {len(train_loader)}")
print(f"Total testing batches: {len(test_loader)}")

Total training batches: 2500
Total testing batches: 625

# Building ANN model

In [107]:
class LoanANN(nn.Module):
    def __init__(self):
        super(LoanANN, self).__init__()
        self.fc1 = nn.Linear(100, 64)
        self.fc2 = nn.Linear(64, 32)
        self.fc3 = nn.Linear(32, 1)
        self.relu = nn.ReLU()           # hidden layers ke liye
        self.sigmoid = nn.Sigmoid()     # output ko 0–1 range mein laata hai
    
    def forward(self, x):                  # Forward Function Flow
        x = self.relu(self.fc1(x))
        x = self.relu(self.fc2(x))
        x = self.sigmoid(self.fc3(x))
        return x

model = LoanANN()
print(model)

LoanANN(
  (fc1): Linear(in_features=100, out_features=64, bias=True)
  (fc2): Linear(in_features=64, out_features=32, bias=True)
  (fc3): Linear(in_features=32, out_features=1, bias=True)
  (relu): ReLU()
  (sigmoid): Sigmoid()
)

# Defining Loss Function and Optimizer

In [108]:
criterion = nn.BCELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

print(criterion)
print(optimizer)

# Loss batata hai kitni galti hai, optimizer us galti ko thik karta hai

BCELoss()
Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: None
    lr: 0.001
    maximize: False
    weight_decay: 0
)

# Training the Model

In [109]:
epochs = 10

for epoch in range(epochs):
    model.train()
    total_loss = 0
    
    for X_batch, y_batch in train_loader:
        optimizer.zero_grad()
        y_pred = model(X_batch)
        loss = criterion(y_pred.squeeze(), y_batch)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    
    avg_loss = total_loss / len(train_loader)
    print(f"Epoch {epoch+1}/{epochs} - Loss: {avg_loss:.4f}")

Epoch 1/10 - Loss: 0.0925
Epoch 2/10 - Loss: 0.0637
Epoch 3/10 - Loss: 0.0595
Epoch 4/10 - Loss: 0.0562
Epoch 5/10 - Loss: 0.0548
Epoch 6/10 - Loss: 0.0532
Epoch 7/10 - Loss: 0.0511
Epoch 8/10 - Loss: 0.0497
Epoch 9/10 - Loss: 0.0479
Epoch 10/10 - Loss: 0.0467

In [110]:
# Har batch pe: predict → error → learn → improve
# Forward → Loss → Backward → Update → Repeat
# ye training ho rhi and loss calculate and kam kiya jaa rha hai loss

# Evaluting the model

In [111]:
model.eval()

with torch.no_grad():
    y_pred = model(X_test_tensor)
    y_pred_class = (y_pred.squeeze() > 0.5).float()

from sklearn.metrics import accuracy_score, classification_report

y_pred_np = y_pred_class.numpy()
y_test_np = y_test_tensor.numpy()

print(f"Accuracy: {accuracy_score(y_test_np, y_pred_np):.4f}")
print()
print(classification_report(y_test_np, y_pred_np))

Accuracy: 0.9829

              precision    recall  f1-score   support

         0.0       0.98      0.89      0.93      2715
         1.0       0.98      1.00      0.99     17285

    accuracy                           0.98     20000
   macro avg       0.98      0.95      0.96     20000
weighted avg       0.98      0.98      0.98     20000